---
version: '3.4'
services:
  weaviate:
    runtime: nvidia
    command:
    - --host
    - '0.0.0.0'
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.2
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'  # 端口不能变
      # 'http://localhost:8080'  http://t2v-transformers:8080
      # weaviate提供的text2vect-transformers:custom镜像有bug，需要手动修改AutoTokenizer加载方式为use_fast=False
      # 若推理服务与weaviate服务分离，则指定TRANSFORMERS_INFERENCE_API:'http://localhost:8080'，且省略t2v-transformers模块配置
      # 若推理服务与weaviate服务合一，则TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'并配置t2v-transformers模块
      # 但实测至少bge-large-zh-v1.5不能单独启动，因此不能使用'http://localhost:8080'
      # RERANKER_INFERENCE_API: 'http://reranker-transformers:8080' 
      # reranker仅支持部分指定的模型，不推荐使用
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,backup-filesystem' # backup-filesystem is only compatible with single-node backups
      CLUSTER_HOSTNAME: 'node1'
      # 鉴权与权限控制
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'pmvdb001,pmvdb002'
      AUTHENTICATION_APIKEY_USERS: 'pmvdbuser1,pmvdbuser2'
      AUTHORIZATION_ADMINLIST_ENABLE: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'pmvdbuser1'
      AUTHORIZATION_ADMINLIST_READONLY_USERS: 'pmvdbuser2'
      # 备份路径
      BACKUP_FILESYSTEM_PATH: /home/pinming/data/weaviate/backup
  t2v-transformers:
    image: bge-large-v1.5-zh
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy: # 按照https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html在宿主机上按照container-toolkit
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu] 
            count: 1
  # reranker-transformers:
  #   image: semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
  #   environment:
  #     ENABLE_CUDA: '1'
  #     NVIDIA_VISIBLE_DEVICES: 'all'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - capabilities:
  #           - 'gpu'
volumes:
  weaviate_data:
...